services:
  bitsongd:
    image: ${IMAGE:-ghcr.io/bitsongofficial/go-bitsong:feat-hyperlane}
    container_name: ${CHAIN_ID:-crescendo-1}
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    environment:
      - CHAIN_ID=${CHAIN_ID:-crescendo-1}
      - VAL_NAME=${VAL_NAME:-val1}
      - MODE=${MODE:-genesis}
      - GENESIS_URL=${GENESIS_URL:-}
      - SEEDS=${SEEDS:-}
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    volumes:
      - bitsongd-data:/bitsongd/.data
      - bitsongd-accounts:/accounts
      - ../files/entrypoint.sh:/entrypoint.sh:ro

volumes:
  bitsongd-data:
  bitsongd-accounts:
