name: Gentx
on:
  pull_request:
    paths:
      - "bitsong-local/gentx/*.json"
jobs:
  verify-gentx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gentx-validation
        run: |
          bash -x ./scripts/verify-gentx.sh
